language: r
r:
  - release
  - devel
sudo: false
cache: packages
dist: trusty
latex: true
r_check_args: '--ignore-vignettes'
r_build_args: '--no-build-vignettes'

r_packages:
  - remotes
  - knitr
  - testthat

env:
  global:
    - MAKEFLAGS="-j 2"

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars
  - R -e 'remotes::install_version("roxygen2", "6.1.0")'


script:
  - |
    travis_wait 100 R CMD build .
    travis_wait 100 R CMD check metaBMA*tar.gz

after_script:
  - tar -ztvf metaBMA_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 100 tar -C .. -xf $PKG_TARBALL

after_failure:
  - cat metaBMA.Rcheck/00*
