language: r
sudo: true
cache: packages
dist: trusty
r_check_args: '--ignore-vignettes'
r_build_args: '--no-build-vignettes'

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      r_binary_packages:
        - devtools
        - Rcpp
        - RcppEigen
        - mvtnorm
        - rstan
        - StanHeaders
        - LaplacesDemon
        - logspline
        - testthat
      r_packages:
        - remotes
        - knitr
        - rmarkdown
        - coda
        - rstantools
        - bridgesampling
        - BH
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      r: devel
      r_binary_packages:
        - devtools
        - Rcpp
        - RcppEigen
        - mvtnorm
        - rstan
        - StanHeaders
        - LaplacesDemon
        - logspline
        - testthat
      r_packages:
        - remotes
        - knitr
        - rmarkdown
        - coda
        - rstantools
        - bridgesampling
        - BH
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

script:
  - |
    travis_wait 30 R CMD build .
    travis_wait 5 R CMD check metaBMA*tar.gz --as-cran

after_script:
  - tar -ztvf metaBMA_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 10 tar -C .. -xf $PKG_TARBALL

after_failure:
  - cat metaBMA.Rcheck/00*
