language: r
dist: trusty
latex: true

warnings_are_errors: TRUE
r_check_args: '--ignore-vignettes'
r_build_args: '--no-build-vignettes'

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

env:
  - _R_CHECK_FORCE_SUGGESTS_=true
    _R_CHECK_CRAN_INCOMING_=true

cache:
  - packages
  - ccache

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

matrix:
  include:
    - r: release
      r_binary_packages:
        - devtools
        - Rcpp
        - RcppEigen
        - mvtnorm
        - rstan
        - StanHeaders
        - LaplacesDemon
        - logspline
        - testthat
      r_packages:
        - remotes
        - knitr
        - rmarkdown
        - coda
        - rstantools
        - bridgesampling
        - BH
    - r: devel
      r_binary_packages:
        - devtools
        - Rcpp
        - RcppEigen
        - mvtnorm
        - rstan
        - StanHeaders
        - LaplacesDemon
        - logspline
        - testthat
      r_packages:
        - remotes
        - knitr
        - rmarkdown
        - coda
        - rstantools
        - bridgesampling
        - BH

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fext-numeric-literals -fPIC" >> ~/.R/Makevars

notifications:
  email:
  on_success: change
  on_failure: change
