// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4fixed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4fixed_jzs_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4random_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4random_H0_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4random_dstudy_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4random_jzs_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4random_jzs_dstudy_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4random_ordered_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4fixed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4fixed_mod, 0},
    {"_rcpp_module_boot_stan_fit4fixed_jzs_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4fixed_jzs_mod, 0},
    {"_rcpp_module_boot_stan_fit4random_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4random_mod, 0},
    {"_rcpp_module_boot_stan_fit4random_H0_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4random_H0_mod, 0},
    {"_rcpp_module_boot_stan_fit4random_dstudy_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4random_dstudy_mod, 0},
    {"_rcpp_module_boot_stan_fit4random_jzs_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4random_jzs_mod, 0},
    {"_rcpp_module_boot_stan_fit4random_jzs_dstudy_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4random_jzs_dstudy_mod, 0},
    {"_rcpp_module_boot_stan_fit4random_ordered_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4random_ordered_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_metaBMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
