# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("fixed", "fixed_jzs", "random", "random_H0", "random_dstudy", "random_jzs", "random_jzs_dstudy", "random_ordered")

# load each stan module
Rcpp::loadModule("stan_fit4fixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4fixed_jzs_mod", what = TRUE)
Rcpp::loadModule("stan_fit4random_mod", what = TRUE)
Rcpp::loadModule("stan_fit4random_H0_mod", what = TRUE)
Rcpp::loadModule("stan_fit4random_dstudy_mod", what = TRUE)
Rcpp::loadModule("stan_fit4random_jzs_mod", what = TRUE)
Rcpp::loadModule("stan_fit4random_jzs_dstudy_mod", what = TRUE)
Rcpp::loadModule("stan_fit4random_ordered_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
